### Site Settings ###
title               : Jiwon Jung
description         : >-
                      Hello, I am Jiwon
                      <br/>
                      <strong>Software Engineer</strong> focused on <strong>AI</strong>, <strong>VR/AR</strong>, 
                      <br/> <strong>Programming</strong> & <strong>Game Development</strong>.

baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : g1jung/g1jung.github.io           # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects and navbar only)
# markdown            : kramdown


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html


### Author Info ###
author:
  name              : Jiwon Jung
  image             : assets/home/4.jpg       #https://i.imgur.com/uyDNQnn.jpg
# behance           : your_username
# dribbble          : your_username
  email             : jjwon6218@gmail.com
# facebook          : your_username
  github            : g1jung
# gitlab            : your_username
  instagram         : aeffines
# kaggle            : your_username
  linkedin          : jiwon-jung-608a01209
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                         # Set true to enable analytics
  google:
    tracking_id: G-R7N2XVNE51


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - _projects/(1) PlaceHolder Project.md
  - _projects/(2) Awesome Project.md
  - _projects/(3) Empty Project.md
  - _projects/(4) VVG on GitHub.md
  - _projects/(5) The Fabulous.md
  - _projects/(6) Dummy Project.md